---
name: 'Upload Metrics Action'
description: 'GitHub action to build and run Googletest cases'
author: 'Grahame White'
inputs:
  connection-string:
    description: 'Connection string for the database to be used'
    required: true
    default: 'NOT SET'
  metrics-collection:
    description: 'the collection to add the metrics to'
    required: true
    default: 'summary'
  metrics-path:
    description: 'relative path to json metrics file to be uploaded'
    required: true
    default: 'metrics/summary.json'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/apollo-fire/metrics-test-action:v0.0.1'
  args:
    - ${{ inputs.connection-string }}
    - ${{ inputs.metrics-collection }}
    - ${{ inputs.metrics-path }}
branding:
  icon: 'code'
  colour: 'orange'
